#pragma once

#define NO_ERROR 0
#define COLUMNS_OF_ONE_MATRIX_NOT_EQUALS_ROWS_OF_OTHER -1
#define NEGATIVE_OFFSET -2 
#define MATRIXES_NOT_THE_SAME_LENGTH -3
#define BAD_SIZES_OF_VECTORS -4
#define MATRIX_IS_NOT_SQUARE -5
#define TOO_BIG_OFFSET -6
#define ITS_NOT_A_MATRIX_BAD_SIZES -7
#define ERROR_CANT_OPEN_FILE -8
#define BAD_VALUE_IN_THE_FILE -9
#define INCORECT_VALUE_IN_FILE -10;
